### ISSUE TITLE
control MousePosition - ne fonctionne pas avec toutes les projections

### ISSUE THREAD

**Issue by Gaetanbrl** [mviewer/mviewer#722]
## Environnement

Version mviewer: 3.9.1-snapshot

Navigateur: nom / version

## Description

Lorsqu'on utilise une projection qui n'est pas connue par OpenLayers, on observe une erreur lors du survol de la souris sur la carte.

Code lié : 
https://github.com/mviewer/mviewer/blob/5fc0e76df5bcb651d3d32b7ed7511c904ec3cb7f/js/mviewer.js#L326

## Ce que je devrai voir

Aucune erreur dans la console.

## Etapes

1. Passer l'application en EPSG:32620.
2. Passer la souris sur la carte
3. Voir l'erreur dans la console

![image](https://user-images.githubusercontent.com/16317988/210379831-38c3916c-3f30-4b3a-93a4-d9502af2c992.png)

```
Uncaught TypeError: Cannot read properties of null (reading 'getCode')
    at qi (proj.js:466:39)
    at Hi (proj.js:488:10)
    at Object.$i [as transform] (proj.js:506:25)
    at coordinateFormat (mviewer.js:326:23)
    at _T.control.MousePosition.updateHTML_ (MousePosition.js:263:18)
    at _T.control.MousePosition.handleMouseMove (MousePosition.js:175:10)
```

**Comment by Gaetanbrl** [comment]
Si on déclare la projection au préalable alors il n'y a plus d'erreur : 

```
// register projection
proj4.defs("EPSG:32620","+proj=utm +zone=20 +datum=WGS84 +units=m +no_defs +type=crs");
ol.proj.proj4.register(proj4)

// use projection
projection = new Projection({
  code: 'EPSG:32620',
  extent: [166021.44, 0.0, 833978.56, 9329005.18],
});
```
